### ISSUE TITLE
Mejoras Miguel

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/PictogramsPredictionsLibrary#2]
Según el plan de trabajo se plantea realizar las siguientes mejoras y optimización

- [x] Mejorar los resultado de frases largas
- [x] Incluir resultados con varias palabras por opción
- [x] Introducir backoff the manera eficiente

**Comment by miguel1abag** [comment]
Cambios realizados:
- Mejora de resultados para frases largas, acortando el N-grama inicial para aquellos que no daban buenos resultados en una primera evaluación.
- Mejora de los resultados de conjugación

Estos cambios apenas suponen un aumento del 0,5% en el tiempo de ejecución.
Dejo archivo Excel con las mismas frases evaluadas, indicando en verde los nuevos resultados.
Actualizo el código en GIT.

[EjemploFrasesOTTA.xlsx](https://github.com/OTTAA-Project/PictogramsPredictionsLibrary/files/6447544/EjemploFrasesOTTA.xlsx)

**Comment by miguel1abag** [comment]
Cambios realizados:
- Inclusión del cálculo de backoff de forma simplificada. Mejora resultados de aquellas frases iniciales que no aparecen completamente en el diccionario.

Estos cambios suponen un aumento del 7,3% en el tiempo de ejecución.
Dejo archivo Excel con las mismas frases evaluadas.

Actualizo el código en GIT. Subo nuevos archivos por si no queréis utilizar esta versión.
Los archivos añadidos son los siguientes:
- viterbiNbestBackoff
- calcularPrediccionBackoff
- scriptPredictionBackoff

[EjemploFrasesOTTA.xlsx](https://github.com/OTTAA-Project/PictogramsPredictionsLibrary/files/6469022/EjemploFrasesOTTA.xlsx)

**Comment by miguel1abag** [comment]
Cambios realizados:
- Se sigue iterando el algoritmo para dar como resultado más de una palabra (se ha limitado a 3)

No se recomienda utilizar por el momento esta versión debido a la escasa mejora en los resultados ofrecidos y al aumento en 3,26 veces en tiempo de ejecución. Esta función tendrá más utilidad cuando se personalice el algoritmo en función de los usos de cada usuario.
Actualizo Excel con las mismas frases evaluadas.

Actualizo el código en GIT. Subo nuevos archivos por si no queréis utilizar esta versión.
Los archivos añadidos son los siguientes:
- viterbiNbestMultPal
- calcularPrediccionMultPal
- scriptPredictionMultPal

**Comment by miguel1abag** [comment]
Como cierre de estos trabajos, adjunto informe de optimización actualizado.

[Mejoras Optimización Tiempos - Fase 1 N-gramas - Rev. 1.pdf](https://github.com/OTTAA-Project/PictogramsPredictionsLibrary/files/6503711/Mejoras.Optimizacion.Tiempos.-.Fase.1.N-gramas.-.Rev.1.pdf)

**Comment by lopezjuanma96** [comment]
Miguel, estuve probando el algoritmo con la ultima actualización de main, te comento cosas con las que me encontré:

- Me pareció muy buena la mejora en las predicciones, los tiempos de predicción en su mayoría rondan el tiempo promedio del archivo, y comparé las respuestas que obteníamos con los primeros Excel a las actuales y son mucho más correctas.
- Sé que en el documento ponías que no convenía todavía probar los algoritmos de Backoff y MultiPalabras porque no estaban terminados, pero se me ocurrió probarlos de todas maneras para observar ese aumento de tiempo que me comentabas, me encontré con estos problemas:

1. Los import no estaban arreglados, por ejemplo en el scriptPredictionBackoff.py se hacía import de calcularPrediccion y no de calcularPrediccionBackoff, luego en calcularPrediccionBackoff.py se hacía import de viterbiNbest en vez de viterbiNbestBackoff, lo cual generaba errores porque los argumentos no son los mismos. Eso seguramente lo hayas notado y corregido pero no se haya subido todavía, pero lo comento por las dudas.
2. Para el script de predicción con Backoff busqué alguna frase que no tuviera chances de estar en el diccionario, me pareció probar con "Los átomos" y "Los átomos son", para lo que obtuve el siguiente log:
`scriptPrediction.py
Abrir archivos: 0.45186781883239746
Los átomos :  {'1': 'quiero', '2': 'hola', '3': 'yo', '4': 'estás'} tiempo: 0.5455927848815918
Los átomos :  {'1': 'quiero', '2': 'hola', '3': 'yo', '4': 'estás'} tiempo sin apertura: 0.07886028289794922

python scriptPredictionBackoff.py
Abrir archivos: 0.5467872619628906
Traceback (most recent call last):
File "scriptPredictionBackoff.py", line 59, in <module>
json_pathsConjugated = calcularPrediccion(sentence, maxNgram, maxNumPaths, listWords, listWordsInf, dictNgram, dictNgramInf, dictBackoff, dictBackoffInf, verbs_array, listDefaultPaths)
File "D:\OTTAA - Lixi\PictogramsPredictionsLibrary\calcularPrediccionBackoff.py", line 37, in calcularPrediccion          pathsSelected = viterbiNbest(sentenceInf, maxNgram, maxNumPaths, listWordsInf, dictNgramInf, dictBackoffInf, listDefaultPaths)  #Se ejecuta el algoritmo Viterbi para obtener las predicciones de continuación de la frase inicial
File "D:\OTTAA - Lixi\PictogramsPredictionsLibrary\viterbiNbestBackoff.py", line 54, in viterbiNbest                      nGramBack.append(sentenceWords[0]) #Se añade la primera palabra de la parte final de la frase (evaluación diccionario) para incluirla en backoff 
IndexError: list index out of range                                                                                                                                                                                                             

scriptPrediction.py 
Abrir archivos: 0.5014212131500244
Los átomos son :  {'1': 'mi', '2': 'aburrido', '3': 'bueno', '4': 'barón'} tiempo: 1.314720630645752
Los átomos son :  {'1': 'mi', '2': 'aburrido', '3': 'bueno', '4': 'barón'} tiempo sin apertura: 0.8114087581634521

scriptPredictionBackoff.py
Abrir archivos: 0.531609296798706 
Los átomos son :  {'1': 'mi', '2': 'aburrido', '3': 'bueno', '4': 'barón'} tiempo: 1.379220962524414
Los átomos son :  {'1': 'mi', '2': 'aburrido', '3': 'bueno', '4': 'barón'} tiempo sin apertura: 0.8255889415740967`

Tal vez te sea de utilidad analizar los resultados y el error que se me generó en "Los átomos" con Backoff

3. Entiendo que el script de MultiPalabra funciona de manera que al hacer las predicciones de 4 palabras de una frase, puedas solicitar, si es que existen, otros set de 4 palabras que sigan en orden de importancia, pero no encontré como lograr esto con el scriptPredictionMultPal.py. Esto puede ser porque yo no haya entendido bien como funciona el script, o porque cómo mencionaste en el archivo, todavía está en desarrollo en cuyo caso no habría ningún problema.

Son más que nada comentarios que puedan servirte para detectar problemas y mejoras, cualquier otra cosa que quieras que pruebe o si hace falta charlar de algo por videollamada avisanos!

**Comment by miguel1abag** [comment]
Hola Juanma,

Te respondo en orden a tus útiles aportaciones:
- Perfecto. Era el objetivo con las mejoras principales realizadas.
- Los algoritmos de Backoff y MultiPalabras se pueden probar y utilizar. Lo único que los resultados no aportan valor, actualmente, en comparación con el aumento en el tiempo de ejecución que suponen respecto al algoritmo principal.

Respecto a los errores:
1.  Cierto, había errores con los 'import'. Ocurre lo mismo con la versión MultiPalabra. He subido la nueva versión de todos los archivos, corrigiendo este punto.
2. Había un bug en los algoritmos Backoff y MultiPalabras si la última palabra de la frase inicial no estaba en el diccionario. Corregido y subida nuevas versiones.
3. El algoritmo MultiPalabra genera resultados de hasta N palabras por cada solución (por defecto, dejé este parámetro en ' maxNumWords = 3' pero lo podéis cambiar sin problema), en vez de generar resultados de 1 palabra como hasta ahora.
Por ejemplo, para la frase inicial 'Hola', se consigue el resultado 'buenas tardes' cuando en el algoritmo principal solo se sugiere 'buenas'. 
Si tienes más dudas, lo comentamos sin problema.

Seguimos en contacto para otros asuntos que puedan surgir y para el comienzo de la segunda fase.
